### ISSUE TITLE
How to get the SDevo.jar to work?

### ISSUE THREAD

**Issue by jmfa** [nicfel/SDevo#1]
Hi,

Thanks for this very interesting package.
I've downloaded the SDevo.jar file but whenever I try to use it I keep getting "Error: Invalid or corrupt jarfile"
How exactly am I supposed to install/use it?

Thank you very much in advance,
Joao

**Comment by nicfel** [comment]
Dear @jmfa,

I now added a BEAUti interface to SDevo with the following [commit]( https://github.com/nicfel/SDevo/commit/de26b52ba67fb6399edb82634bfa4aaefd7cbc86). Setting up the xml is fairly straightforward and works like setting up BDMM-prime. The installation process etc. is described on the readme https://github.com/nicfel/SDevo
